"""Machine table

Revision ID: 23ba5fe7c414
Revises: 
Create Date: 2020-10-01 14:20:38.210765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ba5fe7c414'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=8), nullable=True),
    sa.Column('serialnum', sa.String(length=64), nullable=True),
    sa.Column('customer', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_project'), 'machine', ['project'], unique=True)
    op.create_index(op.f('ix_machine_serialnum'), 'machine', ['serialnum'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_serialnum'), table_name='machine')
    op.drop_index(op.f('ix_machine_project'), table_name='machine')
    op.drop_table('machine')
    # ### end Alembic commands ###
