"""Kit table

Revision ID: 30c047bc3dd7
Revises: 23ba5fe7c414
Create Date: 2020-10-02 09:13:43.621222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c047bc3dd7'
down_revision = '23ba5fe7c414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=8), nullable=True),
    sa.Column('serialnum', sa.Integer(), nullable=True),
    sa.Column('customer', sa.String(length=64), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['serialnum'], ['machine.serialnum'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kit_project'), 'kit', ['project'], unique=False)
    op.drop_index('ix_machine_project', table_name='machine')
    op.create_index(op.f('ix_machine_project'), 'machine', ['project'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_project'), table_name='machine')
    op.create_index('ix_machine_project', 'machine', ['project'], unique=1)
    op.drop_index(op.f('ix_kit_project'), table_name='kit')
    op.drop_table('kit')
    # ### end Alembic commands ###
