"""product line field

Revision ID: 3f2d002a703a
Revises: 30c047bc3dd7
Create Date: 2020-10-06 16:32:37.955861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2d002a703a'
down_revision = '30c047bc3dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('prodline', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'prodline')
    # ### end Alembic commands ###
